spring.application.name=axon
server.port=8080

telegram.bot.token=${TELEGRAM_TOKEN}
telegram.bot.base.url=${TELEGRAM_API_BASE_URL}

# PostgreSQL connection
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Flyway properties
spring.flyway.enabled=true
spring.flyway.url=${DATABASE_URL}
spring.flyway.password=${DATABASE_PASSWORD}
spring.flyway.user=${DATABASE_USERNAME}
spring.flyway.schemas=migrations
spring.flyway.locations=classpath:db/migration/postgresql